[tool.poetry]
name = "minimal-python-project-boilerplate"
version = "0.1.0"
description = ""
authors = ["yukiyan <wakayama0215@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
pynput = "^1.7.6"
